### PR TITLE
added the possibility to configure an emptyEntryTemplate for combobox…

### PR DESCRIPTION
**Pull request by szerhusenBC**
This request is related to ticket #27 in the trivial components project.

### CODE REVIEW

**Comment by szerhusenBC** [comment]
please wait with this request, I have to fix an error, that depends on this change!

**Comment by szerhusenBC** [comment]
Ok, now you could merge the changes if you want ;)

**Comment by szerhusenBC** [comment]
I'm closing this request now, because we will do some more things on our fork and we don't want to map all this commits on this request.

**Comment by yamass** [comment]
Hi Stephan,

first of all, thank you for your pull request and sorry for being a little bit unresponsive at the moment (being in Bali).

I am currently a little unhappy with the template "switching" your commits would introduce. Nonetheless, it makes total sense. I will think about it and, if I don't come up with an alternative, accept this new complexity. 

By the way, this will need to be pretty well tested (manually).

Cheers
Yann

**Comment by szerhusenBC** [comment]
I'm not that happy with this solution as well. I hope you'll find a better way ;)

**Comment by yamass** [comment]
How about the following: 

* No more need to specify a `tr-editor-area`. If you do not specify one, the editor will fall back to filling the whole template (see #28). 
* The emptyTemplate may (but does not have to) specify a `tr-editor-area`
* No template switching needed for positioning the input field as both templates provide the necessary information. The only kind of "template switching" (or rather "choosing") will appear in `selectEntry()`

This is a minimally invasive change as far as I can see. Will this satisfy your needs?

**Comment by szerhusenBC** [comment]
Yeah, this sounds good so far. Would like to the behavior of this solution.

**Comment by yamass** [comment]
Please check,

**Pull request merged**
